# Generated by Django 5.0.6 on 2024-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/coffe_1.png', upload_to='static/images/'),
        ),
    ]
